"""Add nested comments support

Revision ID: 0763563e7a50
Revises: c456bba37d67
Create Date: 2026-02-10 03:21:15.073942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0763563e7a50'
down_revision = 'c456bba37d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_comment_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_harkness_comments_parent_comment_id'), ['parent_comment_id'], unique=False)
        batch_op.create_foreign_key('fk_harkness_comments_parent', 'harkness_comments', ['parent_comment_id'], ['comment_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_harkness_comments_parent', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_harkness_comments_parent_comment_id'))
        batch_op.drop_column('parent_comment_id')

    # ### end Alembic commands ###
