"""add_gemini_ocr_fields_to_ocr_history

Revision ID: 083c165e9a3c
Revises: 9ff7fc80a6ad
Create Date: 2026-02-11 23:51:39.559056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083c165e9a3c'
down_revision = '9ff7fc80a6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('corrected_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ocr_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_history', schema=None) as batch_op:
        batch_op.drop_column('ocr_method')
        batch_op.drop_column('corrected_text')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
