"""add_zoom_link_and_access_log

Revision ID: 0985cb82058c
Revises: dfa21565ed10
Create Date: 2026-02-11 02:48:27.141495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0985cb82058c'
down_revision = 'dfa21565ed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_access_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('zoom_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zoom_access_logs_accessed_at'), ['accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_zoom_access_logs_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zoom_access_logs_teacher_id'), ['teacher_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zoom_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zoom_token', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_zoom_token'), ['zoom_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_zoom_token'))
        batch_op.drop_column('zoom_token')
        batch_op.drop_column('zoom_link')

    with op.batch_alter_table('zoom_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zoom_access_logs_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_zoom_access_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_zoom_access_logs_accessed_at'))

    op.drop_table('zoom_access_logs')
    # ### end Alembic commands ###
