"""Add teacher board and attachments

Revision ID: 0cde9cc2785b
Revises: f137914464cc
Create Date: 2026-02-10 02:39:41.575595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cde9cc2785b'
down_revision = 'f137914464cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_boards',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_notice', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id')
    )
    with op.batch_alter_table('teacher_boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_boards_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_boards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_boards_is_notice'), ['is_notice'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_boards_title'), ['title'], unique=False)

    op.create_table('teacher_board_attachments',
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['teacher_boards.board_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    with op.batch_alter_table('teacher_board_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_board_attachments_board_id'), ['board_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_board_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_board_attachments_board_id'))

    op.drop_table('teacher_board_attachments')
    with op.batch_alter_table('teacher_boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_boards_title'))
        batch_op.drop_index(batch_op.f('ix_teacher_boards_is_notice'))
        batch_op.drop_index(batch_op.f('ix_teacher_boards_created_at'))
        batch_op.drop_index(batch_op.f('ix_teacher_boards_author_id'))

    op.drop_table('teacher_boards')
    # ### end Alembic commands ###
