"""Add MBTI and parent sharing to consultation records

Revision ID: 1d0ebff11163
Revises: f50c91ec62b9
Create Date: 2026-02-17 17:29:15.434449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0ebff11163'
down_revision = 'f50c91ec62b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_mbti_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recommended_teaching_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teaching_recommendations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('share_with_parents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parent_shared_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_records', schema=None) as batch_op:
        batch_op.drop_column('parent_shared_at')
        batch_op.drop_column('share_with_parents')
        batch_op.drop_column('teaching_recommendations')
        batch_op.drop_column('recommended_teaching_style')
        batch_op.drop_column('student_mbti_type')

    # ### end Alembic commands ###
