"""Add library models (HallOfFame, AdmissionInfo)

Revision ID: 25afd70f0de5
Revises: 0763563e7a50
Create Date: 2026-02-10 03:37:42.481281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25afd70f0de5'
down_revision = '0763563e7a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_info',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_grades', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('admission_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_info_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_info_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_info_expire_date'), ['expire_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_info_is_important'), ['is_important'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_info_publish_date'), ['publish_date'], unique=False)

    op.create_table('hall_of_fame',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('award_name', sa.String(length=200), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('hall_of_fame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_of_fame_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_hall_of_fame_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hall_of_fame_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_of_fame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_is_published'))
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_created_at'))
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_category'))

    op.drop_table('hall_of_fame')
    with op.batch_alter_table('admission_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_info_publish_date'))
        batch_op.drop_index(batch_op.f('ix_admission_info_is_important'))
        batch_op.drop_index(batch_op.f('ix_admission_info_expire_date'))
        batch_op.drop_index(batch_op.f('ix_admission_info_created_at'))
        batch_op.drop_index(batch_op.f('ix_admission_info_category'))

    op.drop_table('admission_info')
    # ### end Alembic commands ###
