"""Add ParentLinkRequest model for admin-approved parent-child linking

Revision ID: 2bd6c5fc9fc1
Revises: 7b9eefe90dff
Create Date: 2026-02-09 23:52:37.271146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd6c5fc9fc1'
down_revision = '7b9eefe90dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_link_requests',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_birth_date', sa.Date(), nullable=True),
    sa.Column('student_grade', sa.String(length=20), nullable=True),
    sa.Column('student_school', sa.String(length=200), nullable=True),
    sa.Column('relation_type', sa.String(length=20), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('matched_student_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matched_student_id'], ['students.student_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('parent_link_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_link_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_link_requests_matched_student_id'), ['matched_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_link_requests_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_link_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_link_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_link_requests_status'))
        batch_op.drop_index(batch_op.f('ix_parent_link_requests_parent_id'))
        batch_op.drop_index(batch_op.f('ix_parent_link_requests_matched_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_link_requests_created_at'))

    op.drop_table('parent_link_requests')
    # ### end Alembic commands ###
