"""add inquiry tables, site_content, teacher_intro fields

Revision ID: 3bcd43f55321
Revises: 812fc1f4c175
Create Date: 2026-02-26 00:50:18.412709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcd43f55321'
down_revision = '812fc1f4c175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'inquiry_posts' not in existing_tables:
        op.create_table('inquiry_posts',
        sa.Column('inquiry_id', sa.String(length=36), nullable=False),
        sa.Column('author_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('is_private', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('inquiry_id')
        )

    if 'site_contents' not in existing_tables:
        op.create_table('site_contents',
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('key')
        )

    if 'inquiry_replies' not in existing_tables:
        op.create_table('inquiry_replies',
        sa.Column('reply_id', sa.String(length=36), nullable=False),
        sa.Column('inquiry_id', sa.String(length=36), nullable=False),
        sa.Column('author_id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
        sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry_posts.inquiry_id'], ),
        sa.PrimaryKeyConstraint('reply_id')
        )

    # users 테이블 컬럼 체크 후 추가
    user_cols = {c['name'] for c in inspector.get_columns('users')}
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'country' not in user_cols:
            batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        if 'city' not in user_cols:
            batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        if 'teacher_intro' not in user_cols:
            batch_op.add_column(sa.Column('teacher_intro', sa.Text(), nullable=True))
        if 'teacher_intro_public' not in user_cols:
            batch_op.add_column(sa.Column('teacher_intro_public', sa.Boolean(), nullable=True))

    # students 테이블 컬럼 체크 후 추가
    student_cols = {c['name'] for c in inspector.get_columns('students')}
    with op.batch_alter_table('students', schema=None) as batch_op:
        if 'country' not in student_cols:
            batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        if 'city' not in student_cols:
            batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('teacher_intro_public')
        batch_op.drop_column('teacher_intro')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('inquiry_replies')
    op.drop_table('site_contents')
    op.drop_table('inquiry_posts')
    # ### end Alembic commands ###
