"""Add harkness board system

Revision ID: 4820c3738124
Revises: 0cde9cc2785b
Create Date: 2026-02-10 02:58:58.454609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4820c3738124'
down_revision = '0cde9cc2785b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harkness_boards',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('board_type', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id')
    )
    with op.batch_alter_table('harkness_boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harkness_boards_board_type'), ['board_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_boards_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_boards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_boards_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_boards_is_active'), ['is_active'], unique=False)

    op.create_table('harkness_posts',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_notice', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['harkness_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('harkness_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harkness_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_posts_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_posts_is_notice'), ['is_notice'], unique=False)

    op.create_table('harkness_comments',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['harkness_posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('harkness_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harkness_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_comments_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harkness_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_harkness_comments_author_id'))

    op.drop_table('harkness_comments')
    with op.batch_alter_table('harkness_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harkness_posts_is_notice'))
        batch_op.drop_index(batch_op.f('ix_harkness_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_harkness_posts_board_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_posts_author_id'))

    op.drop_table('harkness_posts')
    with op.batch_alter_table('harkness_boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harkness_boards_is_active'))
        batch_op.drop_index(batch_op.f('ix_harkness_boards_created_by'))
        batch_op.drop_index(batch_op.f('ix_harkness_boards_created_at'))
        batch_op.drop_index(batch_op.f('ix_harkness_boards_course_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_boards_board_type'))

    op.drop_table('harkness_boards')
    # ### end Alembic commands ###
