"""add_consultation_records

Revision ID: 578a628b063d
Revises: 083c165e9a3c
Create Date: 2026-02-13 01:06:47.753217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578a628b063d'
down_revision = '083c165e9a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_quiz_results')
    op.drop_table('schema_quiz_sessions')
    op.drop_table('schema_quizzes')
    op.drop_table('vocabulary_quiz_sessions')
    op.drop_table('schema_quiz_results')
    op.drop_table('vocabulary_quizzes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_quizzes',
    sa.Column('quiz_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('meaning', sa.TEXT(), nullable=False),
    sa.Column('example', sa.TEXT(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('grade_start', sa.VARCHAR(length=10), nullable=False),
    sa.Column('grade_end', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quiz_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=200), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('schema_quiz_results',
    sa.Column('result_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quiz_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_answer', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('attempted_at', sa.DATETIME(), nullable=True),
    sa.Column('time_taken_seconds', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['schema_quizzes.quiz_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['schema_quiz_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('vocabulary_quiz_sessions',
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), nullable=False),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('correct_count', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('schema_quizzes',
    sa.Column('quiz_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('term', sa.VARCHAR(length=200), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.Column('example', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('grade_start', sa.VARCHAR(length=10), nullable=False),
    sa.Column('grade_end', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quiz_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=200), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('schema_quiz_sessions',
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), nullable=False),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('correct_count', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('vocabulary_quiz_results',
    sa.Column('result_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quiz_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_answer', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('attempted_at', sa.DATETIME(), nullable=True),
    sa.Column('time_taken_seconds', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['vocabulary_quizzes.quiz_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###
