"""Add teaching materials and videos

Revision ID: 7b9eefe90dff
Revises: a08c8489c8fb
Create Date: 2026-02-09 04:50:24.546874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9eefe90dff'
down_revision = 'a08c8489c8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_materials',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    with op.batch_alter_table('teaching_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_materials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_materials_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_materials_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_materials_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_materials_publish_date'), ['publish_date'], unique=False)

    op.create_table('videos',
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_publish_date'), ['publish_date'], unique=False)

    op.create_table('teaching_material_downloads',
    sa.Column('download_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['teaching_materials.material_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('download_id')
    )
    op.create_table('video_views',
    sa.Column('view_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id')
    )
    # courses 테이블이 존재할 때만 인덱스 추가 (신규 DB에는 아직 없을 수 있음)
    conn = op.get_bind()
    tables = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='courses'")).fetchall()
    if tables:
        with op.batch_alter_table('courses', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_courses_availability_status'), ['availability_status'], unique=False)
            batch_op.create_index(batch_op.f('ix_courses_course_type'), ['course_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_courses_grade'), ['grade'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_grade'))
        batch_op.drop_index(batch_op.f('ix_courses_course_type'))
        batch_op.drop_index(batch_op.f('ix_courses_availability_status'))

    op.drop_table('video_views')
    op.drop_table('teaching_material_downloads')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_publish_date'))
        batch_op.drop_index(batch_op.f('ix_videos_is_public'))
        batch_op.drop_index(batch_op.f('ix_videos_grade'))
        batch_op.drop_index(batch_op.f('ix_videos_end_date'))
        batch_op.drop_index(batch_op.f('ix_videos_created_at'))

    op.drop_table('videos')
    with op.batch_alter_table('teaching_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_materials_publish_date'))
        batch_op.drop_index(batch_op.f('ix_teaching_materials_is_public'))
        batch_op.drop_index(batch_op.f('ix_teaching_materials_grade'))
        batch_op.drop_index(batch_op.f('ix_teaching_materials_end_date'))
        batch_op.drop_index(batch_op.f('ix_teaching_materials_created_at'))

    op.drop_table('teaching_materials')
    # ### end Alembic commands ###
