"""add_class_board_models

Revision ID: 844c53a2428b
Revises: f2b8cef0c780
Create Date: 2026-02-10 23:55:48.051816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844c53a2428b'
down_revision = 'f2b8cef0c780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_board_posts',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_notice', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('class_board_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_board_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_board_posts_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_board_posts_created_at'), ['created_at'], unique=False)

    op.create_table('class_board_comments',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['class_board_posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('class_board_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_board_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_board_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_board_comments_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_board_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_board_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_class_board_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_class_board_comments_author_id'))

    op.drop_table('class_board_comments')
    with op.batch_alter_table('class_board_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_board_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_class_board_posts_course_id'))
        batch_op.drop_index(batch_op.f('ix_class_board_posts_author_id'))

    op.drop_table('class_board_posts')
    # ### end Alembic commands ###
