"""Add participation and understanding scores to weekly evaluations

Revision ID: 8ab95646c4e5
Revises: 138804b9d190
Create Date: 2026-02-18 10:44:46.014142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab95646c4e5'
down_revision = '138804b9d190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participation_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('understanding_score', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_evaluations', schema=None) as batch_op:
        batch_op.drop_column('understanding_score')
        batch_op.drop_column('participation_score')

    # ### end Alembic commands ###
