"""add_teaching_material_files

Revision ID: 8e602ed5ed61
Revises: 8ab95646c4e5
Create Date: 2026-02-20 23:37:10.397907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e602ed5ed61'
down_revision = '8ab95646c4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_material_files',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['teaching_materials.material_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    with op.batch_alter_table('teaching_material_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_material_files_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_material_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_material_files_material_id'))

    op.drop_table('teaching_material_files')
    # ### end Alembic commands ###
