"""add_harkness_question_template_fields

Revision ID: 9817222745d8
Revises: 8e602ed5ed61
Create Date: 2026-02-21 01:23:46.430111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9817222745d8'
down_revision = '8e602ed5ed61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harkness_question_likes',
    sa.Column('like_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['harkness_posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('post_id', 'question_number', 'user_id', name='unique_question_user_like')
    )
    with op.batch_alter_table('harkness_question_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harkness_question_likes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_question_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_question_likes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('harkness_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_harkness_comments_question_number'), ['question_number'], unique=False)

    with op.batch_alter_table('harkness_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question1_intent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question2_intent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question3_intent', sa.Text(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('question3_intent')
        batch_op.drop_column('question3')
        batch_op.drop_column('question2_intent')
        batch_op.drop_column('question2')
        batch_op.drop_column('question1_intent')
        batch_op.drop_column('question1')

    with op.batch_alter_table('harkness_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harkness_comments_question_number'))
        batch_op.drop_column('question_number')

    with op.batch_alter_table('harkness_question_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harkness_question_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_question_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_question_likes_created_at'))

    op.drop_table('harkness_question_likes')
    # ### end Alembic commands ###
