"""Initial migration: User, Student, Essay models

Revision ID: 9d9c1697241b
Revises: 
Create Date: 2026-02-06 11:36:06.873436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9c1697241b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('students',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('essays',
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('essay_id')
    )
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essays_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_essays_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_essays_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_essays_user_id'), ['user_id'], unique=False)

    op.create_table('essay_notes',
    sa.Column('note_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    with op.batch_alter_table('essay_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_notes_essay_id'), ['essay_id'], unique=False)

    op.create_table('essay_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('html_path', sa.String(length=500), nullable=True),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('essay_id', 'version_number', name='uq_essay_version')
    )
    with op.batch_alter_table('essay_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_versions_essay_id'), ['essay_id'], unique=False)

    op.create_table('essay_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('html_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('final_grade', sa.String(length=10), nullable=True),
    sa.Column('ai_detection_score', sa.Integer(), nullable=True),
    sa.Column('plagiarism_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['essay_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    with op.batch_alter_table('essay_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_results_essay_id'), ['essay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_essay_results_version_id'), ['version_id'], unique=False)

    op.create_table('essay_scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='check_score_range'),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['essay_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id')
    )
    with op.batch_alter_table('essay_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_scores_essay_id'), ['essay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_essay_scores_version_id'), ['version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essay_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_scores_version_id'))
        batch_op.drop_index(batch_op.f('ix_essay_scores_essay_id'))

    op.drop_table('essay_scores')
    with op.batch_alter_table('essay_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_results_version_id'))
        batch_op.drop_index(batch_op.f('ix_essay_results_essay_id'))

    op.drop_table('essay_results')
    with op.batch_alter_table('essay_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_versions_essay_id'))

    op.drop_table('essay_versions')
    with op.batch_alter_table('essay_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_notes_essay_id'))

    op.drop_table('essay_notes')
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essays_user_id'))
        batch_op.drop_index(batch_op.f('ix_essays_student_id'))
        batch_op.drop_index(batch_op.f('ix_essays_status'))
        batch_op.drop_index(batch_op.f('ix_essays_created_at'))

    op.drop_table('essays')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_students_name'))

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
