"""Add profile image fields to User model

Revision ID: a08c8489c8fb
Revises: da514e96ce6a
Create Date: 2026-02-08 22:44:33.670765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08c8489c8fb'
down_revision = 'da514e96ce6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_path')
        batch_op.drop_column('profile_image_filename')

    # ### end Alembic commands ###
