"""add version to reading_mbti_tests

Revision ID: b6eb88b3f0cc
Revises: a3b7e45b5f25
Create Date: 2026-02-21 23:46:43.785157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eb88b3f0cc'
down_revision = 'a3b7e45b5f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'students', ['target_student_id'], ['student_id'], ondelete='SET NULL')

    with op.batch_alter_table('reading_mbti_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_mbti_tests', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
