"""Add harkness post likes

Revision ID: c456bba37d67
Revises: 4820c3738124
Create Date: 2026-02-10 03:17:45.079983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c456bba37d67'
down_revision = '4820c3738124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harkness_post_likes',
    sa.Column('like_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['harkness_posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_post_user_like')
    )
    with op.batch_alter_table('harkness_post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harkness_post_likes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_post_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harkness_post_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harkness_post_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_post_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_harkness_post_likes_created_at'))

    op.drop_table('harkness_post_likes')
    # ### end Alembic commands ###
