"""add post_format to harkness_boards

Revision ID: c5c5ac90ab0a
Revises: 9817222745d8
Create Date: 2026-02-21 16:23:59.840367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c5ac90ab0a'
down_revision = '9817222745d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_format', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harkness_boards', schema=None) as batch_op:
        batch_op.drop_column('post_format')

    # ### end Alembic commands ###
