"""add notification_replies table

Revision ID: c95c6859ee55
Revises: c5c5ac90ab0a
Create Date: 2026-02-21 16:40:26.947542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95c6859ee55'
down_revision = 'c5c5ac90ab0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_replies',
    sa.Column('reply_id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reply_id')
    )
    with op.batch_alter_table('notification_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_replies_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_replies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_replies_notification_id'), ['notification_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_replies_notification_id'))
        batch_op.drop_index(batch_op.f('ix_notification_replies_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_replies_author_id'))

    op.drop_table('notification_replies')
    # ### end Alembic commands ###
