"""Add school and birth_date to students

Revision ID: ccd9672c62af
Revises: 2bd6c5fc9fc1
Create Date: 2026-02-10 01:29:48.909733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd9672c62af'
down_revision = '2bd6c5fc9fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('birth_date')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
