"""Add attachment fields to Essay model

Revision ID: da514e96ce6a
Revises: 074bf59733b2
Create Date: 2026-02-08 22:17:41.610774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da514e96ce6a'
down_revision = '074bf59733b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))

    # Add tier column first if it doesn't exist
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tier_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_tier'), ['tier'], unique=False)

    # Add role_level column first if it doesn't exist
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_level', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_role_level'), ['role_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_level'))
        batch_op.drop_column('role_level')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_tier'))
        batch_op.drop_column('tier_updated_at')
        batch_op.drop_column('tier')

    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_column('attachment_path')
        batch_op.drop_column('attachment_filename')

    # ### end Alembic commands ###
