"""Add Reading MBTI system tables

Revision ID: dfa21565ed10
Revises: 844c53a2428b
Create Date: 2026-02-11 01:05:38.072912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa21565ed10'
down_revision = '844c53a2428b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_mbti_tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('reading_mbti_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=20), nullable=False),
    sa.Column('type_key', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('combo_description', sa.String(length=200), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('reading_style', sa.Text(), nullable=True),
    sa.Column('speaking_style', sa.Text(), nullable=True),
    sa.Column('writing_style', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_code'),
    sa.UniqueConstraint('type_key')
    )
    op.create_table('reading_mbti_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['reading_mbti_tests.test_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('reading_mbti_responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['reading_mbti_tests.test_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('reading_mbti_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('read_type', sa.String(length=20), nullable=False),
    sa.Column('speech_type', sa.String(length=20), nullable=False),
    sa.Column('write_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['reading_mbti_responses.response_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['reading_mbti_tests.test_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['reading_mbti_types.type_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_mbti_results')
    op.drop_table('reading_mbti_responses')
    op.drop_table('reading_mbti_questions')
    op.drop_table('reading_mbti_types')
    op.drop_table('reading_mbti_tests')
    # ### end Alembic commands ###
