"""Add discount fields to payments

Revision ID: f137914464cc
Revises: ccd9672c62af
Create Date: 2026-02-10 01:49:03.037058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f137914464cc'
down_revision = 'ccd9672c62af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discount_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_period', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_period')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_rate')
        batch_op.drop_column('discount_type')
        batch_op.drop_column('original_amount')

    # ### end Alembic commands ###
