"""Add description to Video and recommendation_reason to Book

Revision ID: f2b8cef0c780
Revises: 25afd70f0de5
Create Date: 2026-02-10 05:02:24.764319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b8cef0c780'
down_revision = '25afd70f0de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('recommendation_reason')

    # ### end Alembic commands ###
