"""add_student_profiles_table

Revision ID: f50c91ec62b9
Revises: 578a628b063d
Create Date: 2026-02-14 22:56:09.920031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50c91ec62b9'
down_revision = '578a628b063d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('parent_contact', sa.String(length=50), nullable=True),
    sa.Column('current_school', sa.String(length=100), nullable=True),
    sa.Column('reading_experience', sa.String(length=50), nullable=True),
    sa.Column('reading_competency', sa.Integer(), nullable=True),
    sa.Column('weekly_reading_amount', sa.String(length=50), nullable=True),
    sa.Column('preferred_genres', sa.Text(), nullable=True),
    sa.Column('personality_traits', sa.Text(), nullable=True),
    sa.Column('main_improvement_goal', sa.String(length=200), nullable=True),
    sa.Column('preferred_class_style', sa.String(length=200), nullable=True),
    sa.Column('teacher_request', sa.Text(), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('education_info_needs', sa.Text(), nullable=True),
    sa.Column('academic_goals', sa.Text(), nullable=True),
    sa.Column('career_interests', sa.Text(), nullable=True),
    sa.Column('other_interests', sa.Text(), nullable=True),
    sa.Column('sibling_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
