"""add correction_attachments table

Revision ID: f7441b089d4e
Revises: e3f1a2b4c5d6
Create Date: 2026-02-24 05:46:24.411275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7441b089d4e'
down_revision = 'e3f1a2b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_attachments',
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['essay_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    with op.batch_alter_table('correction_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_attachments_essay_id'), ['essay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_attachments_version_id'), ['version_id'], unique=False)

    # assignments FK는 SQLite에서 이미 존재하므로 생략
    # with op.batch_alter_table('assignments', schema=None) as batch_op:
    #     batch_op.create_foreign_key('fk_assignments_target_student', 'students', ['target_student_id'], ['student_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('assignments', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_assignments_target_student', type_='foreignkey')

    with op.batch_alter_table('correction_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_attachments_version_id'))
        batch_op.drop_index(batch_op.f('ix_correction_attachments_essay_id'))

    op.drop_table('correction_attachments')
    # ### end Alembic commands ###
